function analysis_viewer()
%% ANALYSIS_VIEWER Interactive viewer for phonon analysis results
%
% Provides a file tree interface to browse analysis results with:
% - Left panel: File tree navigation
% - Center panel: Plot display (both .fig and .png)
% - Right panel: Description of analysis type, expected results, filepath
%
% Usage:
%   analysis_viewer
%
% Author: Gerbode Lab
% Date: 2026

%% ==================== CONFIGURATION ====================
% Default analysis output folder
default_path = 'Z:\Colloid Cru\Spring 2026\sorins files\gerbodelabclaude\analysis_output';

%% ==================== BUILD UI ====================
fig = uifigure('Name', 'Analysis Viewer', 'Position', [50 50 1600 900]);
fig.Color = [0.15 0.15 0.15];

% ---- Left panel: File tree ----
pnl_tree = uipanel(fig, 'Title', 'Experiments', ...
    'Position', [8 8 280 884], ...
    'BackgroundColor', [0.2 0.2 0.2], 'ForegroundColor', 'w');

% Path selector
uilabel(pnl_tree, 'Text', 'Analysis Folder:', 'Position', [8 850 100 18], ...
    'FontColor', 'w', 'FontSize', 10);
ef_path = uieditfield(pnl_tree, 'Value', default_path, ...
    'Position', [8 825 220 22]);
btn_browse = uibutton(pnl_tree, 'Text', '...', 'Position', [232 825 35 22], ...
    'BackgroundColor', [0.3 0.3 0.4]);

% Tree view
tree = uitree(pnl_tree, 'Position', [8 8 260 810], ...
    'BackgroundColor', [0.15 0.15 0.15], 'FontColor', 'w');

% ---- Center panel: Plot display ----
pnl_plot = uipanel(fig, 'Title', 'Plot', ...
    'Position', [296 8 900 884], ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', 'w');

% Filepath display
uilabel(pnl_plot, 'Text', 'File:', 'Position', [8 852 30 20], 'FontColor', 'w');
ef_filepath = uieditfield(pnl_plot, 'Value', '', ...
    'Position', [40 852 800 22], 'Editable', 'off', ...
    'BackgroundColor', [0.2 0.2 0.2], 'FontColor', 'cyan');
btn_copy = uibutton(pnl_plot, 'Text', 'Copy', 'Position', [845 852 45 22], ...
    'BackgroundColor', [0.3 0.4 0.3]);

% Plot axes
ax_plot = uiaxes(pnl_plot, 'Position', [8 8 880 835], ...
    'Color', 'k', 'XColor', 'w', 'YColor', 'w');

% ---- Right panel: Description ----
pnl_desc = uipanel(fig, 'Title', 'Analysis Info', ...
    'Position', [1204 8 388 884], ...
    'BackgroundColor', [0.2 0.2 0.2], 'ForegroundColor', 'w');

% Analysis name
uilabel(pnl_desc, 'Text', 'Analysis Type:', 'Position', [8 850 100 18], ...
    'FontColor', 'w', 'FontWeight', 'bold');
lbl_analysis_name = uilabel(pnl_desc, 'Text', '-', ...
    'Position', [8 825 370 22], 'FontColor', 'cyan', 'FontSize', 14);

% Description text area
uilabel(pnl_desc, 'Text', 'Description:', 'Position', [8 795 100 18], ...
    'FontColor', 'w', 'FontWeight', 'bold');
txt_desc = uitextarea(pnl_desc, 'Position', [8 590 370 200], ...
    'Editable', 'off', 'BackgroundColor', [0.15 0.15 0.15], ...
    'FontColor', [0.8 0.8 0.8], 'FontSize', 10);

% Theory section
uilabel(pnl_desc, 'Text', 'Theory / Expected:', 'Position', [8 560 120 18], ...
    'FontColor', 'w', 'FontWeight', 'bold');
txt_theory = uitextarea(pnl_desc, 'Position', [8 355 370 200], ...
    'Editable', 'off', 'BackgroundColor', [0.15 0.15 0.15], ...
    'FontColor', [0.7 0.9 0.7], 'FontSize', 10);

% Interpretation
uilabel(pnl_desc, 'Text', 'Interpretation:', 'Position', [8 325 100 18], ...
    'FontColor', 'w', 'FontWeight', 'bold');
txt_interp = uitextarea(pnl_desc, 'Position', [8 120 370 200], ...
    'Editable', 'off', 'BackgroundColor', [0.15 0.15 0.15], ...
    'FontColor', [0.9 0.9 0.7], 'FontSize', 10);

% Open .fig button
btn_open_fig = uibutton(pnl_desc, 'Text', 'Open in Figure Window', ...
    'Position', [8 80 180 28], 'BackgroundColor', [0.3 0.4 0.5], ...
    'FontWeight', 'bold');
btn_open_folder = uibutton(pnl_desc, 'Text', 'Open Folder', ...
    'Position', [198 80 180 28], 'BackgroundColor', [0.4 0.4 0.3]);

% Data file info
uilabel(pnl_desc, 'Text', 'Data File:', 'Position', [8 50 80 18], 'FontColor', 'w');
lbl_data_file = uilabel(pnl_desc, 'Text', '-', ...
    'Position', [8 28 370 20], 'FontColor', [0.6 0.6 0.6], 'FontSize', 9);

%% ==================== STATE ====================
S = struct();
S.fig = fig;
S.tree = tree;
S.ef_path = ef_path;
S.ef_filepath = ef_filepath;
S.ax_plot = ax_plot;
S.lbl_analysis_name = lbl_analysis_name;
S.txt_desc = txt_desc;
S.txt_theory = txt_theory;
S.txt_interp = txt_interp;
S.lbl_data_file = lbl_data_file;
S.btn_open_fig = btn_open_fig;
S.current_file = '';
S.analysis_info = get_analysis_info();
fig.UserData = S;

%% ==================== WIRE CALLBACKS ====================
btn_browse.ButtonPushedFcn = @(~,~) cb_browse_folder(fig);
btn_copy.ButtonPushedFcn = @(~,~) cb_copy_path(fig);
btn_open_fig.ButtonPushedFcn = @(~,~) cb_open_fig(fig);
btn_open_folder.ButtonPushedFcn = @(~,~) cb_open_folder(fig);
tree.SelectionChangedFcn = @(~,evt) cb_tree_select(fig, evt);

% Load initial tree
populate_tree(fig);

end

%% ==================== CALLBACKS ====================

function cb_browse_folder(fig)
    S = fig.UserData;
    folder = uigetdir(S.ef_path.Value, 'Select Analysis Output Folder');
    if folder ~= 0
        S.ef_path.Value = folder;
        fig.UserData = S;
        populate_tree(fig);
    end
end

function cb_copy_path(fig)
    S = fig.UserData;
    clipboard('copy', S.ef_filepath.Value);
end

function cb_open_fig(fig)
    S = fig.UserData;
    if isempty(S.current_file)
        return;
    end

    % Try to open .fig version
    [folder, name, ~] = fileparts(S.current_file);
    fig_path = fullfile(folder, [name '.fig']);

    if exist(fig_path, 'file')
        openfig(fig_path);
    else
        msgbox('No .fig file found for this plot.', 'Info');
    end
end

function cb_open_folder(fig)
    S = fig.UserData;
    if isempty(S.current_file)
        return;
    end

    folder = fileparts(S.current_file);
    if exist(folder, 'dir')
        if ispc
            winopen(folder);
        elseif ismac
            system(['open "' folder '"']);
        else
            system(['xdg-open "' folder '"']);
        end
    end
end

function cb_tree_select(fig, evt)
    S = fig.UserData;

    if isempty(evt.SelectedNodes)
        return;
    end

    node = evt.SelectedNodes(1);
    if ~isfield(node.NodeData, 'filepath') || isempty(node.NodeData.filepath)
        return;
    end

    filepath = node.NodeData.filepath;

    % Update display
    display_plot(fig, filepath);
end

function populate_tree(fig)
    S = fig.UserData;
    base_path = S.ef_path.Value;

    % Clear existing tree
    delete(S.tree.Children);

    if ~exist(base_path, 'dir')
        return;
    end

    % Get experiment folders
    exp_folders = dir(base_path);
    exp_folders = exp_folders([exp_folders.isdir] & ~startsWith({exp_folders.name}, '.'));

    for i = 1:length(exp_folders)
        exp_name = exp_folders(i).name;
        exp_path = fullfile(base_path, exp_name);

        % Skip documentation folder
        if strcmp(exp_name, 'documentation')
            continue;
        end

        % Create experiment node
        exp_node = uitreenode(S.tree, 'Text', upper(exp_name), ...
            'NodeData', struct('filepath', '', 'type', 'experiment'));

        % Check for summary plots at experiment level
        summary_files = dir(fullfile(exp_path, '*_summary.png'));
        for j = 1:length(summary_files)
            [~, name, ~] = fileparts(summary_files(j).name);
            uitreenode(exp_node, 'Text', ['[Summary] ' name], ...
                'NodeData', struct('filepath', fullfile(exp_path, summary_files(j).name), ...
                'type', get_analysis_type(name)));
        end

        % Get frequency folders
        freq_folders = dir(exp_path);
        freq_folders = freq_folders([freq_folders.isdir] & startsWith({freq_folders.name}, 'f'));

        for j = 1:length(freq_folders)
            freq_name = freq_folders(j).name;
            freq_path = fullfile(exp_path, freq_name);

            % Create frequency node
            freq_node = uitreenode(exp_node, 'Text', freq_name, ...
                'NodeData', struct('filepath', '', 'type', 'frequency'));

            % Get plot files
            plot_files = dir(fullfile(freq_path, '*.png'));

            for k = 1:length(plot_files)
                [~, name, ~] = fileparts(plot_files(k).name);
                file_path = fullfile(freq_path, plot_files(k).name);

                uitreenode(freq_node, 'Text', name, ...
                    'NodeData', struct('filepath', file_path, ...
                    'type', get_analysis_type(name)));
            end
        end
    end

    % Expand first level
    if ~isempty(S.tree.Children)
        expand(S.tree.Children(1));
    end
end

function display_plot(fig, filepath)
    S = fig.UserData;

    % Update filepath display
    S.ef_filepath.Value = filepath;
    S.current_file = filepath;

    % Clear and display image
    cla(S.ax_plot);

    if exist(filepath, 'file')
        try
            img = imread(filepath);
            imshow(img, 'Parent', S.ax_plot);
            S.ax_plot.XColor = 'w';
            S.ax_plot.YColor = 'w';
        catch
            text(S.ax_plot, 0.5, 0.5, 'Unable to load image', ...
                'HorizontalAlignment', 'center', 'Color', 'w', ...
                'Units', 'normalized', 'FontSize', 14);
        end
    end

    % Get analysis type and update description
    [~, name, ~] = fileparts(filepath);
    analysis_type = get_analysis_type(name);

    if isfield(S.analysis_info, analysis_type)
        info = S.analysis_info.(analysis_type);
        S.lbl_analysis_name.Text = info.name;
        S.txt_desc.Value = info.description;
        S.txt_theory.Value = info.theory;
        S.txt_interp.Value = info.interpretation;
    else
        S.lbl_analysis_name.Text = name;
        S.txt_desc.Value = {'No description available for this analysis type.'};
        S.txt_theory.Value = {''};
        S.txt_interp.Value = {''};
    end

    % Check for data file
    [folder, base_name, ~] = fileparts(filepath);
    data_file = fullfile(folder, [base_name '_data.mat']);
    if exist(data_file, 'file')
        S.lbl_data_file.Text = [base_name '_data.mat'];
    else
        S.lbl_data_file.Text = '-';
    end

    fig.UserData = S;
end

function type = get_analysis_type(name)
    % Extract analysis type from filename
    name = lower(name);

    % Check for summary plots first (they have different calculations)
    if contains(name, 'summary')
        if contains(name, 'bode')
            type = 'bode_summary';
        elseif contains(name, 'penetration')
            type = 'penetration_summary';
        elseif contains(name, 'resonance')
            type = 'resonance_summary';
        else
            type = 'summary';
        end
    elseif contains(name, 'bode')
        type = 'bode';
    elseif contains(name, 'fourier')
        type = 'fourier';
    elseif contains(name, 'penetration')
        type = 'penetration';
    elseif contains(name, 'resonance')
        type = 'resonance';
    elseif contains(name, 'anisotropy')
        type = 'anisotropy';
    elseif contains(name, 'momentum')
        type = 'momentum';
    elseif contains(name, 'decomposition')
        type = 'decomposition';
    elseif contains(name, 'vacf') || contains(name, 'dos')
        type = 'vacf';
    elseif contains(name, 'msd')
        type = 'msd';
    elseif contains(name, 'correlation')
        type = 'correlation';
    else
        type = 'unknown';
    end
end

function info = get_analysis_info()
    % Return struct with descriptions for each analysis type
    info = struct();

    info.bode = struct(...
        'name', 'Bode Analysis (Spatial)', ...
        'description', {{...
            'Amplitude and phase of displacement vs position.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. Bin particles by distance from drive (n_bins_spatial)', ...
            '2. Compute complex Fourier amplitude at drive freq for each bin:', ...
            '   U(y) = FFT(displacement)[drive_freq_bin]', ...
            '3. Amplitude(y) = |U(y)|', ...
            '4. Phase(y) = angle(U(y))'}}, ...
        'theory', {{...
            'For a linear viscoelastic system:', ...
            '- Amplitude decays exponentially with distance', ...
            '- Phase accumulates linearly (wave propagation)', ...
            '- Slope of phase gives wavelength/wavevector', ...
            '', ...
            'Expected: Monotonic amplitude decay from drive,', ...
            'smooth phase accumulation indicating traveling wave.'}}, ...
        'interpretation', {{...
            '- Steep amplitude decay = high damping', ...
            '- Shallow decay = good mechanical transmission', ...
            '- Linear phase = traveling wave', ...
            '- Flat phase = evanescent/standing wave', ...
            '- Oscillations may indicate reflections or resonance'}});

    info.fourier = struct(...
        'name', 'Fourier Analysis (Single Frequency)', ...
        'description', {{...
            'Power spectrum of particle displacements at one drive freq.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. Compute displacement from mean: u(t) = x(t) - <x>', ...
            '2. Apply FFT: U(f) = FFT(u)', ...
            '3. Power spectrum: P(f) = |U(f)|^2', ...
            '4. Participation: PR = 1/(N*sum(p_i^2)) where p_i = |U_i|^2/sum'}}, ...
        'theory', {{...
            '- Peaks correspond to resonant modes of the system', ...
            '- Driving frequency should appear prominently', ...
            '- Participation ratio = 1 for extended modes', ...
            '- Participation ratio -> 0 for localized modes', ...
            '', ...
            'Expected: Sharp peak at driving frequency,', ...
            'possible harmonics at 2f, 3f, etc.'}}, ...
        'interpretation', {{...
            '- Sharp peaks = coherent oscillations', ...
            '- Broad peaks = damped/overdamped modes', ...
            '- Multiple peaks = mode coupling', ...
            '- Low participation = localized vibrations', ...
            '- High participation = collective/extended modes'}});

    info.penetration = struct(...
        'name', 'Penetration Depth (Single Frequency)', ...
        'description', {{...
            'Spatial decay profile of response at one drive frequency.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. Get amplitude(y) from Bode analysis', ...
            '2. Fit exponential: A(y) = A0 * exp(-y/delta)', ...
            '3. Penetration depth delta = 1/e decay distance', ...
            '4. Plot amplitude vs distance with fit overlay'}}, ...
        'theory', {{...
            'In overdamped systems:', ...
            'delta ~ sqrt(stiffness/damping) / omega', ...
            '', ...
            '- Higher frequencies penetrate less', ...
            '- Stiffer systems penetrate more', ...
            '- More damped systems penetrate less', ...
            '', ...
            'Expected: Exponential decay of amplitude,', ...
            'frequency-dependent penetration depth.'}}, ...
        'interpretation', {{...
            '- Large delta = good mechanical transmission', ...
            '- Small delta = heavily damped', ...
            '- delta vs frequency reveals material properties', ...
            '- Non-exponential decay suggests nonlinearity', ...
            '- or heterogeneous structure'}});

    info.resonance = struct(...
        'name', 'Resonance Detection', ...
        'description', {{...
            'Identifies resonant frequencies and estimates', ...
            'quality factors (Q) from spectral peak widths.', ...
            '', ...
            'Q = f_resonance / bandwidth measures how', ...
            'sharply the system responds at resonance.'}}, ...
        'theory', {{...
            '- Q > 1: underdamped oscillations', ...
            '- Q < 1: overdamped response', ...
            '- Q = 0.5: critically damped', ...
            '', ...
            'For driven oscillators:', ...
            'Response peaks when drive matches natural frequency', ...
            '', ...
            'Expected: Peak at or near driving frequency,', ...
            'possibly at system natural frequencies.'}}, ...
        'interpretation', {{...
            '- High Q = low damping, sharp resonances', ...
            '- Low Q = broad, overdamped response', ...
            '- Peak at drive freq = forced resonance', ...
            '- Peaks elsewhere = natural modes excited', ...
            '- Multiple peaks = multi-mode behavior'}});

    info.anisotropy = struct(...
        'name', 'Anisotropy Analysis', ...
        'description', {{...
            'Compares mechanical response in different directions', ...
            '(X vs Y displacement).', ...
            '', ...
            'Reveals directional preferences arising from', ...
            'lattice structure, defects, or domain patterns.'}}, ...
        'theory', {{...
            '- Isotropic: equal response in all directions', ...
            '- Anisotropic: directional preference', ...
            '', ...
            'For zigzag/chevron lattices:', ...
            'Expect anisotropy due to alternating buckling', ...
            '', ...
            'For stripe domains:', ...
            'Strong anisotropy along vs perpendicular to stripes'}}, ...
        'interpretation', {{...
            '- Ratio > 1: stronger X response', ...
            '- Ratio < 1: stronger Y response', ...
            '- Ratio ~ 1: isotropic', ...
            '- Angular distribution shows preferred directions', ...
            '- Correlate with domain structure'}});

    info.momentum = struct(...
        'name', 'Momentum Space Analysis', ...
        'description', {{...
            'Computes the dynamical structure factor S(k, omega)', ...
            'to reveal phonon dispersion relations.', ...
            '', ...
            'Shows how frequency relates to wavevector,', ...
            'distinguishing acoustic and optical modes.'}}, ...
        'theory', {{...
            '- Acoustic modes: omega -> 0 as k -> 0', ...
            '- Optical modes: omega > 0 at k = 0', ...
            '- Slope of acoustic branch = sound velocity', ...
            '- Band gaps indicate forbidden frequencies', ...
            '', ...
            'For 2D crystals: expect 2 acoustic branches', ...
            '(longitudinal and transverse)'}}, ...
        'interpretation', {{...
            '- Bright bands = phonon modes', ...
            '- Band slope = group velocity', ...
            '- Flat bands = localized/optical modes', ...
            '- Band gaps = frequency filtering', ...
            '- Broadening = damping/disorder'}});

    info.decomposition = struct(...
        'name', 'Mode Decomposition', ...
        'description', {{...
            'Uses SVD/PCA to decompose motion into orthogonal', ...
            'modes ordered by variance contribution.', ...
            '', ...
            'Each mode captures a collective motion pattern.', ...
            'First modes explain most of the variance.'}}, ...
        'theory', {{...
            '- Eigenvalues give mode importance', ...
            '- Eigenvectors give spatial pattern', ...
            '- Rapid variance decay = few dominant modes', ...
            '- Slow decay = complex multi-scale dynamics', ...
            '', ...
            'For driven systems: expect first mode at drive freq'}}, ...
        'interpretation', {{...
            '- 90% variance in 1-2 modes = simple dynamics', ...
            '- Many modes needed = complex behavior', ...
            '- Mode shapes reveal collective patterns', ...
            '- Compare mode frequencies to drive frequency', ...
            '- Localized modes suggest defects'}});

    info.vacf = struct(...
        'name', 'Velocity Autocorrelation & DOS', ...
        'description', {{...
            'Velocity autocorrelation and density of states.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. Compute velocities: v(t) = [x(t+1) - x(t-1)] / (2*dt)', ...
            '2. VACF(tau) = <v(t) * v(t+tau)> averaged over particles & t', ...
            '3. Normalize: VACF(tau) / VACF(0)', ...
            '4. DOS = Real part of FFT(VACF)', ...
            '', ...
            'VACF shows velocity memory; DOS shows mode distribution.'}}, ...
        'theory', {{...
            '- VACF(0) = mean kinetic energy', ...
            '- VACF decay = velocity decorrelation', ...
            '- Oscillations in VACF = caged motion', ...
            '- DOS peaks = phonon band edges', ...
            '', ...
            'For 2D: DOS ~ omega at low frequency (Debye)'}}, ...
        'interpretation', {{...
            '- Fast VACF decay = rapid thermalization', ...
            '- Oscillations = persistent vibrations', ...
            '- DOS shape reveals dimensionality', ...
            '- DOS peaks = van Hove singularities', ...
            '- Compare to theoretical predictions'}});

    info.msd = struct(...
        'name', 'Mean Squared Displacement', ...
        'description', {{...
            'Tracks how far particles move from initial positions.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. Displacement: dr(t) = r(t) - r(0)', ...
            '2. MSD(t) = <|dr(t)|^2> averaged over all particles', ...
            '3. Fit power law: MSD ~ t^alpha', ...
            '4. Plot MSD vs time on log-log axes', ...
            '', ...
            'alpha = 1: diffusion, alpha < 1: caged, alpha > 1: super'}}, ...
        'theory', {{...
            '- Free particles: alpha = 1 (Brownian)', ...
            '- Confined/caged: alpha < 1 at short times', ...
            '- Driven oscillation: oscillatory MSD', ...
            '- Ballistic motion: alpha = 2', ...
            '', ...
            'For crystals: expect subdiffusive (alpha < 1)'}}, ...
        'interpretation', {{...
            '- alpha ~ 1: diffusive, mobile particles', ...
            '- alpha < 1: confinement, lattice effects', ...
            '- Oscillations: driven oscillatory motion', ...
            '- Plateau at long times: bounded motion', ...
            '- Growth at long times: collective drift'}});

    info.correlation = struct(...
        'name', 'Spatial Correlation Functions', ...
        'description', {{...
            'Computes spatial correlations of displacements', ...
            'at different particle separations.', ...
            '', ...
            'Reveals how mechanical information propagates', ...
            'through the crystal lattice.'}}, ...
        'theory', {{...
            '- C(r) = <u(0) * u(r)> / <u^2>', ...
            '- Decay form reveals interaction range', ...
            '- Exponential: short-range interactions', ...
            '- Power-law: long-range/critical', ...
            '', ...
            'Expected: decay over correlation length xi'}}, ...
        'interpretation', {{...
            '- Long correlation length = collective behavior', ...
            '- Short correlation = localized response', ...
            '- Oscillatory = lattice structure effects', ...
            '- Sign changes = alternating displacements', ...
            '- Compare to lattice constant'}});

    info.unknown = struct(...
        'name', 'Unknown Analysis', ...
        'description', {{'No description available for this analysis type.'}}, ...
        'theory', {{''}}, ...
        'interpretation', {{''}});

    %% ========== SUMMARY PLOTS (Cross-Frequency) ==========
    % These aggregate data across ALL driving frequencies

    info.bode_summary = struct(...
        'name', 'Bode Summary (vs Driving Frequency)', ...
        'description', {{...
            'Response amplitude and phase as a function of DRIVING', ...
            'FREQUENCY, not position. Aggregates across all simulations.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. For each driving frequency f_drive:', ...
            '   a. Load bode_data.mat from that frequency folder', ...
            '   b. Extract amplitude at y = L/4 (1/4 distance from drive)', ...
            '   c. Extract phase at same position', ...
            '2. Plot amplitude(f_drive) in dB: 20*log10(A)', ...
            '3. Plot unwrapped phase(f_drive) in degrees'}}, ...
        'theory', {{...
            'Classical Bode plot of a mechanical system:', ...
            '- Low freq: amplitude ~ constant (quasi-static limit)', ...
            '- Resonance: amplitude peak, phase crosses -90 deg', ...
            '- High freq: amplitude rolls off (-20 dB/decade)', ...
            '- Phase: 0 deg -> -180 deg across resonance', ...
            '', ...
            'Reveals system transfer function H(omega).'}}, ...
        'interpretation', {{...
            '- Peak in amplitude = resonant frequency', ...
            '- Roll-off slope = system order', ...
            '- Phase lag indicates delay/filtering', ...
            '- Multiple peaks = multi-mode behavior', ...
            '- Compare to analytical predictions'}});

    info.penetration_summary = struct(...
        'name', 'Penetration Depth (vs Driving Frequency)', ...
        'description', {{...
            'How penetration depth varies with DRIVING FREQUENCY.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. For each driving frequency f_drive:', ...
            '   a. Load penetration_data.mat from that folder', ...
            '   b. Extract fitted penetration depth delta', ...
            '2. Plot delta vs f_drive on log-log axes', ...
            '', ...
            'X-axis: Driving frequency (Hz)', ...
            'Y-axis: Penetration depth delta (pixels)'}}, ...
        'theory', {{...
            'For overdamped viscoelastic medium:', ...
            'delta ~ 1/sqrt(omega) = 1/sqrt(2*pi*f)', ...
            '', ...
            'Slope on log-log plot:', ...
            '- Slope = -0.5: diffusive penetration', ...
            '- Slope = -1: viscous-dominated', ...
            '- Slope = 0: propagating waves', ...
            '', ...
            'Reveals damping mechanisms and length scales.'}}, ...
        'interpretation', {{...
            '- Steep negative slope = strong frequency filtering', ...
            '- Shallow slope = weak frequency dependence', ...
            '- Plateau at low freq = quasi-static limit', ...
            '- Rolloff at high freq = damping cutoff', ...
            '- Non-power-law = multiple mechanisms'}});

    info.resonance_summary = struct(...
        'name', 'Resonance Summary (vs Driving Frequency)', ...
        'description', {{...
            'Peak response frequency and Q-factor vs drive frequency.', ...
            '', ...
            'CALCULATION STEPS:', ...
            '1. For each driving frequency f_drive:', ...
            '   a. Load resonance_data.mat', ...
            '   b. Get dominant peak frequency f_peak from power spectrum', ...
            '   c. Get Q-factor = f_peak / bandwidth (FWHM)', ...
            '2. Left plot: f_peak vs f_drive (with 1:1 diagonal)', ...
            '3. Right plot: Q vs f_drive', ...
            '', ...
            'The 1:1 line shows where system responds at drive freq.'}}, ...
        'theory', {{...
            'Peak tracks drive freq if system is linear and underdamped.', ...
            'Deviation from 1:1 indicates:', ...
            '- Natural frequency dominates (horizontal bands)', ...
            '- Nonlinear frequency shifting', ...
            '- Mode coupling', ...
            '', ...
            'Q-factor:', ...
            '- Q > 1: underdamped, sharp resonance', ...
            '- Q < 1: overdamped, broad response'}}, ...
        'interpretation', {{...
            '- Points on 1:1 line = driven response', ...
            '- Horizontal clusters = natural frequencies', ...
            '- Q increasing with freq = less damping at high f', ...
            '- Q decreasing = more damping at high f', ...
            '- Q ~ constant = frequency-independent damping'}});

    info.summary = struct(...
        'name', 'Summary Plot', ...
        'description', {{...
            'Cross-frequency summary aggregating results from all', ...
            'individual frequency simulations.', ...
            '', ...
            'These plots show how analysis metrics vary as a function', ...
            'of the DRIVING FREQUENCY, not spatial position.'}}, ...
        'theory', {{'See specific summary type for theory.'}}, ...
        'interpretation', {{'See specific summary type for interpretation.'}});
end
