function stitch_frequency_videos(output_base, experiments, frequencies, opts)
%STITCH_FREQUENCY_VIDEOS Create videos showing evolution across driving frequencies
%
%   stitch_frequency_videos(output_base, experiments, frequencies, opts)
%
%   For each experiment and plot type, creates a video where each frame shows
%   the analysis at a different driving frequency, ordered from low to high.
%   This reveals how the system response evolves with driving frequency.
%
%   Inputs:
%       output_base  - Base analysis output folder (e.g., 'analysis')
%       experiments  - Cell array of experiment structs with .name field
%       frequencies  - Array of driving frequencies in ascending order
%       opts         - Options struct (optional)
%           .frame_rate    - Video frame rate (default: 2 fps)
%           .plot_types    - Cell array of plot types to include (default: all)
%           .video_format  - 'mp4' (default) or 'avi'
%           .add_labels    - Add frequency labels to frames (default: true)
%
%   Example:
%       stitch_frequency_videos('analysis', experiments, 0.001:0.001:0.03);

if nargin < 4
    opts = struct();
end

% Default options
if ~isfield(opts, 'frame_rate'), opts.frame_rate = 2; end
if ~isfield(opts, 'video_format'), opts.video_format = 'mp4'; end
if ~isfield(opts, 'add_labels'), opts.add_labels = true; end
if ~isfield(opts, 'plot_types')
    % All plot types generated by run_full_analysis
    opts.plot_types = {'bode', 'fourier', 'penetration', 'resonance', ...
                       'anisotropy', 'momentum', 'decomposition', ...
                       'vacf_dos', 'msd', 'correlation'};
end

fprintf('\n========== Creating Frequency Evolution Videos ==========\n');

% Create videos output folder
videos_folder = fullfile(output_base, 'videos');
if ~exist(videos_folder, 'dir')
    mkdir(videos_folder);
end

% Sort frequencies to ensure correct order
frequencies = sort(frequencies);

% Process each experiment
for exp_idx = 1:length(experiments)
    exp = experiments{exp_idx};
    exp_name = exp.name;
    exp_folder = fullfile(output_base, exp_name);

    if ~exist(exp_folder, 'dir')
        fprintf('[SKIP] Experiment folder not found: %s\n', exp_name);
        continue;
    end

    fprintf('\n=== %s ===\n', exp_name);

    % Create experiment-specific videos folder
    exp_videos_folder = fullfile(videos_folder, exp_name);
    if ~exist(exp_videos_folder, 'dir')
        mkdir(exp_videos_folder);
    end

    % Process each plot type
    for pt_idx = 1:length(opts.plot_types)
        plot_type = opts.plot_types{pt_idx};

        % Collect frames
        frames = {};
        frame_freqs = [];

        for freq_idx = 1:length(frequencies)
            freq = frequencies(freq_idx);
            freq_str = sprintf('f%.4f', freq);
            img_path = fullfile(exp_folder, freq_str, [plot_type '.png']);

            if exist(img_path, 'file')
                frames{end+1} = img_path;
                frame_freqs(end+1) = freq;
            end
        end

        if isempty(frames)
            fprintf('  [SKIP] No %s images found\n', plot_type);
            continue;
        end

        % Create video
        video_name = sprintf('%s_%s_evolution', exp_name, plot_type);
        if strcmp(opts.video_format, 'mp4')
            video_path = fullfile(exp_videos_folder, [video_name '.mp4']);
            vw = VideoWriter(video_path, 'MPEG-4');
        else
            video_path = fullfile(exp_videos_folder, [video_name '.avi']);
            vw = VideoWriter(video_path, 'Motion JPEG AVI');
        end
        vw.FrameRate = opts.frame_rate;
        vw.Quality = 95;

        try
            open(vw);

            for f_idx = 1:length(frames)
                img = imread(frames{f_idx});

                % Add frequency label if requested
                if opts.add_labels
                    img = add_frequency_label(img, frame_freqs(f_idx), f_idx, length(frames));
                end

                writeVideo(vw, img);
            end

            close(vw);
            fprintf('  [OK] %s (%d frames)\n', plot_type, length(frames));

        catch ME
            fprintf('  [ERROR] %s: %s\n', plot_type, ME.message);
            if isopen(vw)
                close(vw);
            end
        end
    end
end

% Create combined comparison videos (all experiments for same plot type)
fprintf('\n=== Creating Cross-Experiment Comparison Videos ===\n');

for pt_idx = 1:length(opts.plot_types)
    plot_type = opts.plot_types{pt_idx};

    % Check if we have data from multiple experiments
    exp_data = {};
    for exp_idx = 1:length(experiments)
        exp = experiments{exp_idx};
        exp_folder = fullfile(output_base, exp.name);

        % Check if this experiment has images for this plot type
        frames = {};
        for freq_idx = 1:length(frequencies)
            freq = frequencies(freq_idx);
            freq_str = sprintf('f%.4f', freq);
            img_path = fullfile(exp_folder, freq_str, [plot_type '.png']);
            if exist(img_path, 'file')
                frames{end+1} = img_path;
            end
        end

        if ~isempty(frames)
            exp_data{end+1} = struct('name', exp.name, 'frames', {frames});
        end
    end

    if length(exp_data) < 2
        continue;  % Need at least 2 experiments to compare
    end

    % Create side-by-side comparison video
    try
        create_comparison_video(exp_data, frequencies, plot_type, videos_folder, opts);
        fprintf('  [OK] %s comparison (%d experiments)\n', plot_type, length(exp_data));
    catch ME
        fprintf('  [ERROR] %s comparison: %s\n', plot_type, ME.message);
    end
end

fprintf('\n=== Videos saved to: %s ===\n', videos_folder);

end

%% Helper: Add frequency label to image
function img_labeled = add_frequency_label(img, freq, frame_num, total_frames)
    % Add a text overlay with frequency info
    [h, w, ~] = size(img);

    % Create label text
    label_text = sprintf('f = %.4f Hz  [%d/%d]', freq, frame_num, total_frames);

    % Create a simple label bar at top
    bar_height = 40;
    label_bar = uint8(255 * ones(bar_height, w, 3));

    % Add text using insertText if available, otherwise just add bar
    try
        label_bar = insertText(label_bar, [10, 10], label_text, ...
            'FontSize', 18, 'TextColor', [0 0 0], 'BoxOpacity', 0);
    catch
        % insertText not available, use simpler approach
        % Just leave the white bar - user can see from filename
    end

    % Combine
    img_labeled = [label_bar; img];
end

%% Helper: Create side-by-side comparison video
function create_comparison_video(exp_data, frequencies, plot_type, output_folder, opts)
    n_exp = length(exp_data);
    n_frames = length(frequencies);

    % Determine layout (2 cols for 2 exps, 2x2 for 3-4, etc.)
    if n_exp <= 2
        n_rows = 1; n_cols = 2;
    elseif n_exp <= 4
        n_rows = 2; n_cols = 2;
    else
        n_rows = 2; n_cols = 3;
    end

    % Read first image to get dimensions
    sample_img = imread(exp_data{1}.frames{1});
    [img_h, img_w, ~] = size(sample_img);

    % Scale down for reasonable video size
    scale = min(1, 1920 / (n_cols * img_w));
    new_w = round(img_w * scale);
    new_h = round(img_h * scale);

    % Create video
    video_name = sprintf('comparison_%s', plot_type);
    video_path = fullfile(output_folder, [video_name '.mp4']);
    vw = VideoWriter(video_path, 'MPEG-4');
    vw.FrameRate = opts.frame_rate;
    vw.Quality = 95;

    open(vw);

    for freq_idx = 1:n_frames
        freq = frequencies(freq_idx);
        freq_str = sprintf('f%.4f', freq);

        % Create canvas
        canvas = uint8(255 * ones(n_rows * new_h + 60, n_cols * new_w, 3));

        % Add title bar
        title_text = sprintf('Comparison: %s | f = %.4f Hz [%d/%d]', ...
            plot_type, freq, freq_idx, n_frames);
        try
            canvas = insertText(canvas, [20, 15], title_text, ...
                'FontSize', 20, 'TextColor', [0 0 0], 'BoxOpacity', 0);
        catch
            % insertText not available
        end

        % Add each experiment's image
        for exp_idx = 1:n_exp
            if freq_idx <= length(exp_data{exp_idx}.frames)
                img = imread(exp_data{exp_idx}.frames{freq_idx});
                img = imresize(img, [new_h, new_w]);
            else
                img = uint8(200 * ones(new_h, new_w, 3));  % Gray placeholder
            end

            row = floor((exp_idx-1) / n_cols);
            col = mod(exp_idx-1, n_cols);
            y_start = 60 + row * new_h + 1;
            x_start = col * new_w + 1;

            canvas(y_start:y_start+new_h-1, x_start:x_start+new_w-1, :) = img;
        end

        writeVideo(vw, canvas);
    end

    close(vw);
end
